//Chalenge: Guess the Number
const prompt = require("prompt-sync")();
let num = Math.floor(Math.random() * 100 + 1);
let chances = 0;
let guess;
console.log(
  "This is a guessing game. You have to enter a number and if it matches with the number generated by computer, then you win...\n",
);
guess = prompt("Enter your guess number between 1-100: ");
++chances;

do {
  guess = Number.parseInt(guess);
  if (num < guess) {
    console.log("Your guess is greater than the generated number. Try Again!!");
    guess = prompt("Enter again: ");
    guess = Number.parseInt(guess);
    ++chances;
    continue;
  } else if (num > guess) {
    console.log("Your guess is lesser than the generated number. Try Again!!");
    guess = prompt("Enter again: ");
    guess = Number.parseInt(guess);
    ++chances;
    continue;
  }
} while (num != guess);
let score = 100 - chances; //To store the score of your game
console.log(
  "\nCongratulations🥳🥳\nThe number generated was",
  num + " and you guessed it right😁\nYour final score is",
  score,
);
